pipeline {
	environment {
		DOCKER = credentials('GitHub_SPP')
	}

	agent any

	tools {
		maven 'Maven352'
	}

	stages {
		stage('Checkout') {
			steps {
				git 'https://github.com/shaktipp/dmpRepo.git'
			}
		}
		stage('Build') {
			steps {
				sh 'mvn -f DmpMathApp/pom.xml clean compile'
			}
		}
		stage('Test') {
			steps {
				sh 'mvn -f DmpMathApp/pom.xml test'
				junit '**/target/surefire-reports/TEST-*.xml'
				archive 'target/*.jar'
			}
		}
		stage('Package') {
			steps {
				sh 'mvn -f DmpMathApp/pom.xml package'
			}
		}
		stage('Sonar Scan') {
			steps {
				sh 'mvn -f DmpMathApp/pom.xml sonar:sonar'
			}
		}

		stage('Build Image') {
			steps {	
				sh 'DmpMathApp/dmp/docker/Dockerfile'
				sh '$pwd'
				sh 'docker build -t math-image . '
			}

		}

	}
}
