pipeline{
    environment {
      DOCKER = credentials('GitHub_SPP')
    }
    agent any
    /* This builds the actual image; synonymous to
     * docker build on the command line */
    def app = docker.build("math-image:${env.BUILD_ID}", "./dmp/docker")	
	
	tools {
		maven 'Maven352'
	}
	
	stages{
		stage('Checkout'){
			steps {
				git 'https://github.com/shaktipp/dmpRepo.git'
			}			
		}		
		stage('Build') {
			steps {
				sh 'mvn -f DmpMathApp/pom.xml clean compile'
			}					
		}
		stage('Test') {
			steps {
				sh 'mvn -f DmpMathApp/pom.xml test'
				junit '**/target/surefire-reports/TEST-*.xml'
				archive 'target/*.jar'
			}
		}
		stage('Package') {
			steps {
				sh 'mvn -f DmpMathApp/pom.xml package'
			}
		}		
		stage('Sonar Scan') {
			steps {
				sh 'mvn -f DmpMathApp/pom.xml sonar:sonar'
			}
		}
		
		stage('Build and Push image') {
			
			sh 'docker build -f DmpMathApp/dmp/docker/Dockerfile -t math-image .'
			
		}
		
		
	}
}
